# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_button.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(800, 600)
        MainWindow.setWindowIcon(QtGui.QIcon('./images/minecraftblock.ico'))
        MainWindow.setStyleSheet("QScrollArea{border:none;}\n"
"QScrollBar::handle{\n"
"    background-color:#569F55;\n"
"    border-radius:5px;\n"
"}\n"
"QScrollBar::handle:hover{\n"
"    background-color:#68BA67;\n"
"}\n"
"QScrollBar::add-page:vertical,QScrollBar::sub-page:vertical{\n"
"    background:none;\n"
"}\n"
"QScrollBar::sub-line:verticall{\n"
"    background:none;\n"
"    background:none;\n"
"}\n"
"QScrollBar::add-line:verticall{\n"
"    background:none;\n"
"    background:none;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget{background-color:#3D6A3C;}\n"
"QGroupBox{background-color:#3D6A3C;border:none;}\n"
"QPushButton{\n"
"    height:40px;\n"
"    background-color:#569F55;\n"
"    border:none;\n"
"    color:white;\n"
"    font-size:24px;\n"
"    border-radius:3px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:#68BA67;\n"
"}\n"
"QLabel{\n"
"    color:white;\n"
"    font-size:24px;\n"
"}\n"
"QListWidget{border:none;outline:0;}\n"
"QListWidget::item{\n"
"    height:40px;\n"
"     background-color:#569F55;\n"
"     margin-bottom:10px;\n"
"    margin-right:10px;\n"
"    border-radius:3px;\n"
"    color:white;\n"
"}\n"
"QListWidget::item:hover{\n"
"    background-color:#68BA67;\n"
"}\n"
"QListWidget::item:selected{\n"
"    background-color:#7AD478;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, -20, 150, 621))
        self.groupBox.setStyleSheet("QPushButton{background-color:#468245;}\n"
"QPushButton:hover{background-color:#569F55;}\n"
"QGroupBox{background-color:#468245;}")
        self.groupBox.setObjectName("groupBox")
        self.settings = QtWidgets.QPushButton(self.groupBox)
        self.settings.setGeometry(QtCore.QRect(0, 570, 151, 50))
        self.settings.setStyleSheet("")
        self.settings.setObjectName("settings")
        self.logo = QtWidgets.QPushButton(self.groupBox)
        self.logo.setGeometry(QtCore.QRect(20, 30, 111, 101))
        self.logo.setStyleSheet("QPushButton:hover{background-color:#468245;}")
        self.logo.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./images/minecraftblock-1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logo.setIcon(icon)
        self.logo.setIconSize(QtCore.QSize(100, 100))
        self.logo.setObjectName("logo")
        self.versions = QtWidgets.QPushButton(self.groupBox)
        self.versions.setGeometry(QtCore.QRect(0, 200, 151, 50))
        self.versions.setStyleSheet("")
        self.versions.setObjectName("versions")
        self.home = QtWidgets.QPushButton(self.groupBox)
        self.home.setGeometry(QtCore.QRect(0, 150, 151, 50))
        self.home.setObjectName("home")
        self.groupBox_1 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_1.setGeometry(QtCore.QRect(-1, -11, 801, 621))
        self.groupBox_1.setTitle("")
        self.groupBox_1.setObjectName("groupBox_1")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_1)
        self.lineEdit_3.setGeometry(QtCore.QRect(230, 280, 345, 50))
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setStyleSheet("QLineEdit{\n"
"    border:none;\n"
"    border-radius:3px;\n"
"    background-color:#569F55;\n"
"    font-size:20px;\n"
"    color:white;\n"
"}")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_1)
        self.label_3.setGeometry(QtCore.QRect(230, 240, 400, 30))
        self.label_3.setStyleSheet("QLabel{\n"
"    font-size:22px;\n"
"    background-color:#569F55;\n"
"    border-radius:3px;\n"
"    padding-left:5px;\n"
"}")
        self.label_3.setObjectName("label_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_1)
        self.pushButton_4.setGeometry(QtCore.QRect(580, 280, 50, 50))
        self.pushButton_4.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./images/open-folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon1)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_1)
        self.pushButton_5.setGeometry(QtCore.QRect(690, 570, 100, 30))
        self.pushButton_5.setStyleSheet("QPushButton{font-size:20px;}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(150, 0, 651, 601))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.pushButton = QtWidgets.QPushButton(self.page)
        self.pushButton.setGeometry(QtCore.QRect(280, 550, 93, 28))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    width:100px;\n"
"    height:30px;\n"
"    font-size:20px;\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.listWidget = QtWidgets.QListWidget(self.page)
        self.listWidget.setGeometry(QtCore.QRect(130, 140, 400, 390))
        self.listWidget.setObjectName("listWidget")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(570, 0, 71, 41))
        self.label.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.lineEdit = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit.setGeometry(QtCore.QRect(130, 200, 400, 50))
        self.lineEdit.setPlaceholderText(' x.xx.x')
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"    border:1px solid #569F55;\n"
"    border-radius:3px;\n"
"    background-color:#569F55;\n"
"    font-size:20px;\n"
"    color:white;\n"
"    padding-left:10px;\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.listWidget_2 = QtWidgets.QListWidget(self.page_2)
        self.listWidget_2.setGeometry(QtCore.QRect(130, 310, 400, 200))
        self.listWidget_2.setStyleSheet("QListWidget{background-color:#569F55;border-radius:3px;}\n"
"QListWidget::item{height:30px;margin:0;}")
        self.listWidget_2.setObjectName("listWidget_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_2.setGeometry(QtCore.QRect(130, 260, 400, 40))
        self.pushButton_2.setStyleSheet("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_3.setGeometry(QtCore.QRect(470, 250, 50, 50))
        self.pushButton_3.setText("")
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_2.setGeometry(QtCore.QRect(120, 250, 345, 50))
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"    border:none;\n"
"    border-radius:3px;\n"
"    background-color:#569F55;\n"
"    font-size:20px;\n"
"    color:white;\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(self.page_3)
        self.label_2.setGeometry(QtCore.QRect(120, 210, 400, 30))
        self.label_2.setStyleSheet("QLabel{\n"
"    font-size:22px;\n"
"    background-color:#569F55;\n"
"    border-radius:3px;\n"
"    padding-left:5px;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.stackedWidget.addWidget(self.page_3)
        self.groupBox.raise_()
        self.stackedWidget.raise_()
        self.groupBox_1.raise_()
        # message boxes
        self.msg = QtWidgets.QMessageBox()
        self.msg.setIcon(QtWidgets.QMessageBox.Information)
        self.msg.setStyleSheet("QMessageBox{min-width: 300px;}")
        self.msg.setText("Invalid version format")
        self.msg.setWindowTitle("Mods Manager")
        self.msg.setStandardButtons(QtWidgets.QMessageBox.Ok)

        self.msg_2 = QtWidgets.QMessageBox()
        self.msg_2.setIcon(QtWidgets.QMessageBox.Information)
        self.msg_2.setStyleSheet("QMessageBox{min-width: 300px;}")
        self.msg_2.setText("Before activating mods you need to select version")
        self.msg_2.setWindowTitle("Mods Manager")
        self.msg_2.setStandardButtons(QtWidgets.QMessageBox.Ok)

        self.msg_3 = QtWidgets.QMessageBox()
        self.msg_3.setIcon(QtWidgets.QMessageBox.Information)
        self.msg_3.setStyleSheet("QMessageBox{min-width: 300px;}")
        self.msg_3.setText("Mods successfully activated")
        self.msg_3.setWindowTitle("Mods Manager")
        self.msg_3.setStandardButtons(QtWidgets.QMessageBox.Ok)

        self.msg_4 = QtWidgets.QMessageBox()
        self.msg_4.setIcon(QtWidgets.QMessageBox.Information)
        self.msg_4.setStyleSheet("QMessageBox{min-width: 300px;}")
        self.msg_4.setText("Mods for this version are already activated")
        self.msg_4.setWindowTitle("Mods Manager")
        self.msg_4.setStandardButtons(QtWidgets.QMessageBox.Ok)

        self.msg_5 = QtWidgets.QMessageBox()
        self.msg_5.setIcon(QtWidgets.QMessageBox.Information)
        self.msg_5.setStyleSheet("QMessageBox{min-width: 300px;}")
        self.msg_5.setText("There are no mods for this version")
        self.msg_5.setWindowTitle("Mods Manager")
        self.msg_5.setStandardButtons(QtWidgets.QMessageBox.Ok)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mods Manager"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.settings.setText(_translate("MainWindow", "Settings"))
        self.versions.setText(_translate("MainWindow", "Versions"))
        self.home.setText(_translate("MainWindow", "Home"))
        self.label_3.setText(_translate("MainWindow", "Choose mods folder"))
        self.pushButton_5.setText(_translate("MainWindow", "Continue"))
        self.pushButton.setText(_translate("MainWindow", "Activate"))
        self.pushButton_2.setText(_translate("MainWindow", "Add version"))
        self.label_2.setText(_translate("MainWindow", "Mods folder"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
